# BBS Website Link
Host:

accounts:
  - username: 
    password:
#  - username: your_username2
#    password: your_password2

# your_serverchan_sendkey
ftqq_SENDKEY:

# your_BARK_BASE_URL
Bark_BASE_URL:
